namespace HaloDesktop
{
    runtimeclass ConnectViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        String ServerUrl;
        Boolean IsTesting { get; };
        Boolean IsReached { get; };
        Boolean CanTest { get; };
        Boolean CanContinue { get; };
        String StatusText { get; };
        Microsoft.UI.Xaml.Visibility StatusVisibility { get; };
        Windows.Foundation.IAsyncAction TestServerAsync();
        void Continue();
    }

    [default_interface]
    runtimeclass ConnectPage : Microsoft.UI.Xaml.Controls.Page
    {
        ConnectPage();
        ConnectViewModel ViewModel { get; };
    }
}
