namespace HaloDesktop
{
    runtimeclass HomeViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        String HeroTitle { get; };
        String HeroSynopsis { get; };
        String HeroRating { get; };
        String HeroMeta { get; };
        String HeroBackground { get; };
        String ContinueCountLabel { get; };
        Object ContinueItems { get; };
        Object Shelves { get; };
        Int32 FilterIndex { get; };
        Microsoft.UI.Xaml.Visibility ContentVisibility { get; };
        Microsoft.UI.Xaml.Visibility LoadingVisibility { get; };
        Microsoft.UI.Xaml.Visibility ErrorVisibility { get; };
        Microsoft.UI.Xaml.Visibility EmptyVisibility { get; };
        void SetFilter(Int32 index);
        void Retry();
        void OpenDetail(Object item);
        void OpenHeroDetail();
        void OpenHeroSources();
        void OpenContinue(Object item);
        void OpenSearch(String query);
    }

    [default_interface]
    runtimeclass HomePage : Microsoft.UI.Xaml.Controls.Page
    {
        HomePage();
        HomeViewModel ViewModel { get; };
    }
}
