namespace HaloDesktop
{
    runtimeclass HomeViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        String HeroTitle { get; };
        String HeroSynopsis { get; };
        String HeroRating { get; };
        String HeroMeta { get; };
        String HeroBackground { get; };
        String HeroActionLabel { get; };
        String HeroLibraryLabel { get; };
        Boolean HeroLibraryBusy { get; };
        Boolean HeroLibraryEnabled { get; };
        Microsoft.UI.Xaml.Visibility HeroVisibility { get; };
        String HeroLibraryErrorText { get; };
        Microsoft.UI.Xaml.Visibility HeroLibraryErrorVisibility { get; };
        Microsoft.UI.Xaml.Visibility RefreshErrorVisibility { get; };
        String ContinueCountLabel { get; };
        Object ContinueItems { get; };
        Object Shelves { get; };
        Int32 FilterIndex { get; };
        Microsoft.UI.Xaml.Visibility ContentVisibility { get; };
        Microsoft.UI.Xaml.Visibility LoadingVisibility { get; };
        Microsoft.UI.Xaml.Visibility ErrorVisibility { get; };
        Microsoft.UI.Xaml.Visibility EmptyVisibility { get; };
        void SetFilter(Int32 index);
        void Retry();
        void EnsureLoaded();
        void OpenDetail(Object item);
        void OpenHeroDetail();
        void OpenHeroSources();
        void ToggleHeroLibrary();
        void OpenContinue(Object item);
        void OpenSearch(String query);
        void OpenCatalog(Object shelf);
        void OpenContinueCatalog();
        Double HeroHeight { get; };
        Double HeroTitleSize { get; };
        Microsoft.UI.Xaml.Thickness ContentPadding { get; };
    }

    [default_interface]
    runtimeclass HomePage : Microsoft.UI.Xaml.Controls.Page
    {
        HomePage();
        HomeViewModel ViewModel { get; };
    }
}
