namespace HaloDesktop
{
    runtimeclass LibraryViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        Object Items { get; };
        Int32 FilterIndex { get; };
        Int32 SortIndex { get; };
        String AllLabel { get; };
        String MoviesLabel { get; };
        String SeriesLabel { get; };
        Microsoft.UI.Xaml.Visibility ContentVisibility { get; };
        Microsoft.UI.Xaml.Visibility LoadingVisibility { get; };
        Microsoft.UI.Xaml.Visibility ErrorVisibility { get; };
        Microsoft.UI.Xaml.Visibility EmptyVisibility { get; };
        void SetFilter(Int32 index);
        void SetSort(Int32 index);
        void Retry();
        void OpenDetail(Object item);
    }

    [default_interface]
    runtimeclass LibraryPage : Microsoft.UI.Xaml.Controls.Page
    {
        LibraryPage();
        LibraryViewModel ViewModel { get; };
    }
}
