namespace HaloDesktop
{
    [default_interface]
    runtimeclass SourceResolutionItemViewModel
    {
        String Name { get; };
        String Value { get; };
        Microsoft.UI.Xaml.Visibility ResolvedVisibility { get; };
        Microsoft.UI.Xaml.Visibility FailedVisibility { get; };
    }

    [default_interface]
    runtimeclass SourceQualityItemViewModel
    {
        String Label { get; };
        String Count { get; };
        Double Share { get; };
        Microsoft.UI.Xaml.Visibility Quality2160Visibility { get; };
        Microsoft.UI.Xaml.Visibility Quality1080Visibility { get; };
        Microsoft.UI.Xaml.Visibility QualityOtherVisibility { get; };
    }

    [default_interface]
    runtimeclass SourcePickerRuleViewModel
    {
        String Name { get; };
        String Value { get; };
    }

    [default_interface]
    runtimeclass SourceDisplayItemViewModel
    {
        Microsoft.UI.Xaml.Visibility HeaderVisibility { get; };
        Microsoft.UI.Xaml.Visibility RowVisibility { get; };
        String Key { get; };
        String GroupName { get; };
        String GroupNote { get; };
        String GroupCount { get; };
        String Quality { get; };
        String Range { get; };
        String File { get; };
        String Codec { get; };
        String Audio { get; };
        String Languages { get; };
        String StatusLabel { get; };
        String Size { get; };
        String Detail { get; };
        Microsoft.UI.Xaml.Visibility Quality2160Visibility { get; };
        Microsoft.UI.Xaml.Visibility Quality1080Visibility { get; };
        Microsoft.UI.Xaml.Visibility QualityOtherVisibility { get; };
        Microsoft.UI.Xaml.Visibility InstantVisibility { get; };
        Microsoft.UI.Xaml.Visibility CachingVisibility { get; };
        Microsoft.UI.Xaml.Visibility UncachedVisibility { get; };
        Microsoft.UI.Xaml.Visibility OnDiskVisibility { get; };
        Microsoft.UI.Xaml.Visibility UnknownVisibility { get; };
        Microsoft.UI.Xaml.Visibility DetailColumnVisibility { get; };
        Microsoft.UI.Xaml.Visibility CompactSummaryVisibility { get; };
    }

    runtimeclass SourcesViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        Object Items { get; };
        Object ResolutionItems { get; };
        Object QualityItems { get; };
        String Title { get; };
        String Poster { get; };
        String EpisodeLabel { get; };
        String ResolveSummary { get; };
        String AllFilterLabel { get; };
        String InstantFilterLabel { get; };
        String Quality2160FilterLabel { get; };
        String Quality1080FilterLabel { get; };
        String BestQuality { get; };
        String BestRange { get; };
        String BestFile { get; };
        String BestCodec { get; };
        String BestAudio { get; };
        String BestLanguages { get; };
        String BestSize { get; };
        String BestStatusLine { get; };
        String BestStatusBadge { get; };
        Object PickerRules { get; };
        String TeachingTipTitle { get; };
        String TeachingTipBody { get; };
        Boolean TeachingTipOpen { get; };
        Microsoft.UI.Xaml.Visibility ContentVisibility { get; };
        Microsoft.UI.Xaml.Visibility LoadingVisibility { get; };
        Microsoft.UI.Xaml.Visibility ErrorVisibility { get; };
        Microsoft.UI.Xaml.Visibility EmptyVisibility { get; };
        Microsoft.UI.Xaml.Visibility DetailColumnVisibility { get; };
        void Load(Object parameter);
        void SetListWidth(Double width);
        void Retry();
        void SetFilter(Int32 index);
        void DismissTeachingTip();
        void OpenPlayer(String key);
        void OpenBest();
        void OpenSettings();
    }

    [default_interface]
    runtimeclass SourcesPage : Microsoft.UI.Xaml.Controls.Page
    {
        SourcesPage();
        SourcesViewModel ViewModel { get; };
    }
}
