namespace HaloDesktop
{
    [default_interface]
    runtimeclass ArtworkImage : Microsoft.UI.Xaml.Controls.UserControl
    {
        ArtworkImage();
        String SourceUrl;
        String FallbackUrl;
        Double DecodeWidth;
    }
}
