namespace HaloDesktop
{
    [default_interface]
    runtimeclass ContinueCard : Microsoft.UI.Xaml.Controls.UserControl
    {
        ContinueCard();
        String Title;
        String Meta;
        String Poster;
        String EpisodeTag;
        String TimeLeft;
        Double Progress;
        Double CardWidth { get; };
        event Microsoft.UI.Xaml.RoutedEventHandler Click;
    }
}
