namespace HaloDesktop
{
    [default_interface]
    runtimeclass PlaceholderArt : Microsoft.UI.Xaml.Controls.UserControl
    {
        PlaceholderArt();
        String Caption;
        Microsoft.UI.Xaml.CornerRadius ArtCornerRadius;
    }
}
