namespace HaloDesktop
{
    [default_interface]
    runtimeclass SectionHeader : Microsoft.UI.Xaml.Controls.UserControl
    {
        SectionHeader();
        String Title;
        Object RightContent;
        Boolean ShowBack;
        event Microsoft.UI.Xaml.RoutedEventHandler BackClick;
    }
}
