namespace HaloDesktop
{
    [default_interface]
    runtimeclass SectionHeader : Microsoft.UI.Xaml.Controls.UserControl
    {
        SectionHeader();
        String Title;
        String Crumb;
        Object RightContent;
    }
}
