namespace HaloDesktop
{
    [default_interface]
    runtimeclass SettingRow : Microsoft.UI.Xaml.Controls.UserControl
    {
        SettingRow();
        String Label;
        String Hint;
        Object SettingContent;
    }
}
